version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  android:
    build: ./backend
    ports:
      - "6080:6080"
      - "5901:5901"
