version: '3.8'
services:
  android:
    build: ./cloud-android
    ports:
      - "6080:6080"
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm start
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
