version: "3.8"
services:
  # --- existing scanzaclip services (db, backend, frontend) ---

  cloud-android-web:
    build:
      context: ./backend/services/cloud-android-web
      dockerfile: Dockerfile
    container_name: scanzaclip_cloud_android
    ports:
      - "5000:5000"       # backend API / webhooks (internal)
      - "6080:6080"       # optional local noVNC for dev (prod via ALB)
    environment:
      - NODE_ENV=production
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_ENV=${PAYPAL_ENV}
      - OPN_PUBLIC_KEY=${OPN_PUBLIC_KEY}
      - OPN_SECRET_KEY=${OPN_SECRET_KEY}
      - WEBHOOK_URL_BASE=${WEBHOOK_URL_BASE}
    depends_on:
      - db   # ถ้าใช้ shared db
    restart: unless-stopped
