version: "3.8"
services:
  web:
    build: .
    container_name: cloud-android-web
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - OPN_PUBLIC_KEY=${OPN_PUBLIC_KEY}
      - OPN_SECRET_KEY=${OPN_SECRET_KEY}
